/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as AthkarRouteImport } from './routes/athkar'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranReadSurahIdRouteImport } from './routes/quran.read.$surahId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarRoute = AthkarRouteImport.update({
  id: '/athkar',
  path: '/athkar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranReadSurahIdRoute = QuranReadSurahIdRouteImport.update({
  id: '/read/$surahId',
  path: '/read/$surahId',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/athkar': typeof AthkarRoute
  '/habits': typeof HabitsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/read/$surahId': typeof QuranReadSurahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/athkar': typeof AthkarRoute
  '/habits': typeof HabitsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/read/$surahId': typeof QuranReadSurahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/athkar': typeof AthkarRoute
  '/habits': typeof HabitsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/read/$surahId': typeof QuranReadSurahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/athkar' | '/habits' | '/prayers' | '/quran' | '/quran/read/$surahId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/athkar' | '/habits' | '/prayers' | '/quran' | '/quran/read/$surahId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/athkar'
    | '/habits'
    | '/prayers'
    | '/quran'
    | '/quran/read/$surahId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AthkarRoute: typeof AthkarRoute
  HabitsRoute: typeof HabitsRoute
  PrayersRoute: typeof PrayersRoute
  QuranRoute: typeof QuranRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar': {
      id: '/athkar'
      path: '/athkar'
      fullPath: '/athkar'
      preLoaderRoute: typeof AthkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/read/$surahId': {
      id: '/quran/read/$surahId'
      path: '/read/$surahId'
      fullPath: '/quran/read/$surahId'
      preLoaderRoute: typeof QuranReadSurahIdRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface QuranRouteChildren {
  QuranReadSurahIdRoute: typeof QuranReadSurahIdRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranReadSurahIdRoute: QuranReadSurahIdRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AthkarRoute: AthkarRoute,
  HabitsRoute: HabitsRoute,
  PrayersRoute: PrayersRoute,
  QuranRoute: QuranRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
